services:
  postgres:
    image: postgres:16
    container_name: cosmoslog-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cosmoslog
      POSTGRES_USER: cosmoslog
      POSTGRES_PASSWORD: kwohdev132!
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
