server:
  port: 18080

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/cosmoslog_local
    username: cosmoslog
    password: cosmoslog_local_pw
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true # Hibernate가 만든 SQL을 눈으로 확인 가능하게 함.
        jdbc:
          time_zone: Asia/Seoul
    hibernate:
      # flyway를 쓰기 시작하는 시점에서는 validate로 바꿔야 한다. 
      ddl-auto: update # ddl-auto : update -> 엔티티를 기준으로 테이블/컬럼을 자동 생성 및 변경한다.
